# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

permalink: /:categories/:year/:month/:day/:title 

exclude: [".ruby-version", ".ruby-gemset", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
excerpt_separator: <!--more-->

# Site settings
title: yokolet's notelets
tagline: Site Tagline
author:
  name: Yoko Harada
email: yokolet@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yokolet.github.io" # the base hostname & protocol for your site
twitter_username: yokolet
github_username:  yokolet

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

production_url : http://yokolet.github.io
port: 5555

archive_path: /archive.html
categories_path : /categories.html
tags_path : /tags.html
atom_path : /atom.xml
rss_path : /rss.xml

analytics :
  provider : google 
  google : 
    tracking_id : 'UA-761764-5'
